service: appsync-crud-sls-backend
frameworkVersion: "2"

plugins:
  - serverless-appsync-plugin
  #- serverless-esbuild

provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region, 'us-east-1'}

package:
  exclude:
    - package-lock.json
    - package.json

custom:
  appSync:
    - ${file(serverless.appsync-api.yml)}

resources:
  Resources:
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        AutoVerifiedAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: false
            RequireNumbers: false
            RequireUppercase: false
            RequireSymbols: false
        UsernameAttributes:
          - email

  Outputs:
    CognitoUserPoolId:
      Value: !Ref CognitoUserPool
